#pragma once

#include "esp_err.h"
#include "config.h"

#ifdef ABORT_ON_ERROR
#define ERROR(x) ESP_ERROR_CHECK(x)
#else
#define ERROR(x) ESP_ERROR_CHECK_WITHOUT_ABORT(x)
#endif

#define ERROR_FAIL ERROR(ESP_FAIL)
#define ERROR_NO_MEM ERROR(ESP_ERR_NO_MEM)
#define ERROR_INVALID_ARG ERROR(ESP_ERR_INVALID_ARG)
#define ERROR_INVALID_STATE ERROR(ESP_ERR_INVALID_STATE)
#define ERROR_INVALID_SIZE ERROR(ESP_ERR_INVALID_SIZE)
#define ERROR_NOT_FOUND ERROR(ESP_ERR_NOT_FOUND)
#define ERROR_NOT_SUPPORTED ERROR(ESP_ERR_NOT_SUPPORTED)
#define ERROR_NOT_FINISHED ERROR(ESP_ERR_NOT_FINISHED)
#define ERROR_NOT_ALLOWED ERROR(ESP_ERR_NOT_ALLOWED)
#define ERROR_TIMEOUT ERROR(ESP_ERR_TIMEOUT)
